default_stages: [commit, push]
fail_fast: false
repos:
-   repo: local
    hooks:
      - id: zs-jupyter-notebook-cleanup
        name: zs-jupyter-notebook-cleanup
        language: python
        entry: zs-jupyter-notebook-cleanup
        args:
          - --exit-zero # silent mode if possible (but failure if files were modified by this hook)
          - --inplace
          - --remove-outputs
          - --remove-execution-count
          - --remove-empty-cell
          - --remove-spaces-cell
          - --remove-cell-metadata-patterns
          - "scrolled"
          - "collapsed"
          - "execution"
          - "ExecuteTime"
          - --pin-patterns
          - "[pin];[donotremove]"
        files: \.ipynb$
        types: ["file"]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: trailing-whitespace
        always_run: true
#    -   id: end-of-file-fixer
#        always_run: true
    -   id: check-yaml
        always_run: true
    -   id: check-added-large-files
        always_run: true
    -   id: fix-encoding-pragma
        always_run: true

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: ''  # Use the revision sha / tag you want to point at
    hooks:
    -   id: isort
        always_run: true

-   repo: https://github.com/Zoynels/autopep8_quotes
    rev: 'v0.6.3'
    hooks:
    -   id: autopep8_quotes
        args:
        - --exit-zero # silent mode
        always_run: true

-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: ''  # Use the sha / tag you want to point at
    hooks:
    -   id: autopep8
        always_run: true

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    -   id: flake8
        always_run: true
        additional_dependencies: [flake8-quotes]
